import os

DISCORD_PY_BOT_TOKEN = os.getenv('DISCORD_BOT_TOKEN', 'SET_THIS')
DISCORD_PY_COMMAND_PREFEX = "?"
DISCORD_BOT_PATH = 'django_discord.py.bot.example_bot:bot'
DISCORD_BOT_RECONNECT = True
DISCORD_BOT_LOG_HANDLER = None
DISCORD_BOT_LOG_FORMATTER = None
DISCORD_BOT_LOG_LEVEL = None
DISCORD_BOT_ROOT_LOGGER = None
